name: Lint Commits

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-deps
        with:
          path: .github/workflows/dependencies
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        name: Install dependencies
        continue-on-error: true
        run: |
          cd .github/workflows/dependencies
          npm i
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js

      - if: github.event_name == 'push'
        name: Validate current commit with commitlint
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 2
          retry_on: error
          command: |
            cd .github/workflows/dependencies
            npx commitlint --from HEAD~1 --to HEAD --verbose

      - if: github.event_name == 'pull_request'
        name: Validate PR commits with commitlint
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 2
          retry_on: error
          command: |
            cd .github/workflows/dependencies
            npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose